"""App localization keys required by appliance alert subscriptions."""

ALERT_LOCATION_KEYS = {
    101: "fridge_refrigerator_door_open",
    102: "freezer_door_open",
    103: "global_door_is_open_title",
    104: "fridge_wine_temp_changed_notification_title",
    106: "fridge_temp_changed_notification_title",
    107: "freezer_temp_changed_notification_title",
    108: "fridge_water_filter_expired_notification_title",
    109: "fridge_air_filter_expired_notification_title",
    112: "fridge_wine_temp_out_of_range_message",
    113: "ice_door_open",
    114: "ice_clean_required",
    115: "ice_clean_soon",
    116: "ice_clean_add_descale",
    117: "ice_clean_add_sanitizer",
    118: "ice_clean_cancelled",
    119: "ice_clean_complete",
    201: "oven_reached_preheat_temp_notification_title",
    202: "oven_lower_reached_preheat_temp_notification_title",
    203: "oven_meat_probe_in_use_title",
    204: "oven_lower_meat_probe_in_use_notification_title",
    205: "oven_probe_reached_temp_notification_title",
    206: "oven_lower_reached_probe_preheat_temp_notification_title",
    207: "oven_timer1_ended_notification_title",
    208: "oven_timer2_ended_notification_title",
    209: "oven_kitchen_timer1_1min_remaining_notification_title",
    210: "oven_kitchen_timer2_1min_remaining_notification_title",
    211: "oven_cook_timer_ended_notification_title",
    212: "oven_lower_timer_ended_notification_title",
    213: "oven_timer_1min_remaining_notification_title",
    214: "oven_lower_timer_1min_remaining_notification_title",
    215: "oven_meat_probe_10F_set_point_notification_title",
    216: "oven_lower_meat_probe_10F_set_point_notification_title",
    218: "oven_door_ajar_notification_title",
    219: "oven_lower_door_open_notification_title",
    220: "oven_self_clean_complete_notification_title",
    221: "oven_lower_self_clean_complete_notification_title",
    301: "cove_wash_cycle_started_notification_title",
    302: "cove_wash_completed_notification_title",
    303: "fridge_water_softener_low_message",
    304: "cove_rinse_aid_low_notification_title",
    306: "cove_wash_cycle_interrupted_notification_title",
    307: "cove_cycle_cancelled_notification_title",
}

# Ranges name their first and second cavities right and left in the app.
RANGE_ALERT_LOCATION_KEYS = {
    201: "oven_right_reached_preheat_temp_notification_title",
    202: "oven_left_reached_preheat_temp_notification_title",
    203: "oven_right_meat_probe_in_use_notification_title",
    204: "oven_left_meat_probe_in_use_notification_title",
    205: "oven_right_reached_probe_preheat_temp_notification_title",
    206: "oven_left_reached_probe_preheat_temp_notification_title",
    211: "oven_right_timer_ended_notification_title",
    212: "oven_left_timer_ended_notification_title",
    213: "oven_right_timer_1min_remaining_notification_title",
    214: "oven_left_timer_1min_remaining_notification_title",
    215: "oven_right_meat_probe_10F_set_point_notification_title",
    216: "oven_left_meat_probe_10F_set_point_notification_title",
    218: "oven_right_door_open_notification_title",
    219: "oven_left_door_open_notification_title",
    220: "oven_right_self_clean_complete_notification_title",
    221: "oven_left_self_clean_complete_notification_title",
}
